### ISSUE TITLE
Deserializing a json object with a list into tree expecting a list attempts to cast JsonPrimitive to String

### ISSUE THREAD

**Issue by Crupette** [FabLabsMC/fiber#61]
In my POJO object, i have a list of strings that by default contain several values. I create the config tree, and apply the POJO to that tree. I then serialize this tree to a json file to store the values. When I then try to deserialize this json file, the deserializer throws a cast exception stating that it can't cast a JsonPrimitive to a String.
`java.lang.ClassCastException: blue.endless.jankson.JsonPrimitive cannot be cast to java.lang.String
	at io.github.fablabsmc.fablabs.impl.fiber.constraint.StringConstraintChecker.test(StringConstraintChecker.java:11)
	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.SerializableType.test(SerializableType.java:70)
	at io.github.fablabsmc.fablabs.impl.fiber.constraint.ListConstraintChecker.test(ListConstraintChecker.java:40)
	at io.github.fablabsmc.fablabs.impl.fiber.constraint.ListConstraintChecker.test(ListConstraintChecker.java:17)
	at io.github.fablabsmc.fablabs.api.fiber.v1.schema.type.SerializableType.test(SerializableType.java:70)
	at io.github.fablabsmc.fablabs.impl.fiber.tree.ConfigLeafImpl.setValue(ConfigLeafImpl.java:67)
	at io.github.fablabsmc.fablabs.api.fiber.v1.serialization.JanksonSerializer.setPropertyValue(JanksonSerializer.java:140)
	at io.github.fablabsmc.fablabs.api.fiber.v1.serialization.JanksonSerializer.deserialize(JanksonSerializer.java:70)
	at io.github.fablabsmc.fablabs.api.fiber.v1.serialization.JanksonSerializer.deserialize(JanksonSerializer.java:56)`

**Comment by kvverti** [comment]
Fixed in 0.22.0
